# Generated by Django 4.2.6 on 2023-10-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='snippet_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
