# Generated by Django 4.2.6 on 2023-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_snippet_snippet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='details',
            field=models.CharField(max_length=10000000000),
        ),
    ]
