# Generated by Django 4.2.6 on 2023-10-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_snippet_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
