# Generated by Django 4.2.6 on 2023-10-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_snippetimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetimage',
            name='describe',
            field=models.CharField(max_length=10000000000, null=True),
        ),
    ]
