# Generated by Django 4.2.6 on 2023-10-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_snippetimage_describe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetimage',
            name='describe',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='snippet_image',
            field=models.FileField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
