# Generated by Django 4.2.6 on 2023-10-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_remove_snippetimage_describe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
